apiVersion: v1
kind: Service
metadata:
  name: {{ include "woodpecker-ci.fullname" . }}
  labels:
    {{- include "woodpecker-ci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    woodpecker.component: "server"
    {{- include "woodpecker-ci.selectorLabels" . | nindent 4 }}
