apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "woodpecker-ci.fullname" . }}
  labels:
    woodpecker.component: "storage"
    {{- include "woodpecker-ci.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi